export const HOME = "/"
export const ABOUT = "about"
export const LOGIN = "login"
export const KINGDOM_HEARTS = "kingdom-hearts"
export const POKEMON = "pokemon"
export const HERO_ACADEMIA = "My-hero-academia"
export const CART = "cart"
export const PRODUCTS = "products"